Feature/38 alta de puntos de carga fe
FranCagnoli/Cagnoli-Radovitzky-Ya-ez pull request #41
Opened 2022-05-29 23:54 UTC by 402Martin

# :star: Feature: alta de puntos de carga fe
closes: #38

- [Feature/38 alta de puntos de carga fe](https://github.com/FranCagnoli/Cagnoli-Radovitzky-Ya-ez/projects/1)

---

#### Descripcion

Se crea la funcionalidad de los puntos de cargas para el front end. pasando todos los criterios de aceptacion 

---

#### :camera: UI Preview:

Crear un punto de carga:
![image](https://user-images.githubusercontent.com/57497674/170896364-d098d68c-eb83-4079-8de1-35b9cb3d767a.png)
---
Crear un punto de carga sin nombre:
![image](https://user-images.githubusercontent.com/57497674/170896402-157c10ce-6e61-459e-9217-93c2c9b1366d.png)
---
Crear un punto de carga sin descripcion:
![image](https://user-images.githubusercontent.com/57497674/170896450-a4c48b9e-c228-4d04-9902-5c7f4dd1ea7f.png)
---
Crear un punto de carga sin direccion:
![image](https://user-images.githubusercontent.com/57497674/170896489-17ca7eca-f6a3-4eca-b13b-b3bd8cc60e2c.png)

2022-05-30 23:39 UTC, hyanezs requested changes
Cambios a realizar

2022-05-30 23:45 UTC, 402Martin commented on MinTurFrontend/src/app/feature-modules/create-charging-point/create-charging-point.component.ts
> +      this.errorMessages.push('Could not find specified region');
The hole project has the validation of erros also in the front-end, it would be weird to switch only one part to the backend

2022-05-30 23:47 UTC, 402Martin commented on MinTurFrontend/src/app/app-routing.module.ts
> +    CreateCharginPointModule,
![image](https://user-images.githubusercontent.com/57497674/171068854-0eb714d9-f863-4cf0-8469-604d1a1a4c5b.png)

2022-05-30 23:48 UTC, 402Martin commented on MinTurFrontend/src/app/app-routing.module.ts
> +import { CreateCharginPointModule } from './feature-modules/create-charging-point/create-charging-point.module';
![image](https://user-images.githubusercontent.com/57497674/171068881-6c91939d-59f1-4c18-9de6-baad4273b162.png)

2022-05-30 23:49 UTC, 402Martin commented on MinTurFrontend/src/app/core/http-services/charging-points/charging-point.service.ts
> +      newChargingtPoint
![image](https://user-images.githubusercontent.com/57497674/171068936-4417360d-b44d-4289-ae8c-94b827d52118.png)

2022-05-30 23:49 UTC, 402Martin commented on MinTurFrontend/src/app/feature-modules/create-charging-point/create-charging-point.component.ts
> +export class CreateCharginPointComponent implements OnInit {
![image](https://user-images.githubusercontent.com/57497674/171068951-6716acc9-06a7-4b2f-a360-b2dbea35e4c6.png)

2022-06-05 21:56 UTC, hyanezs approved these changes

2022-06-05 22:12 UTC, merged